// Generated by scripts/generate-centroids.ts — do not edit manually
export const REGIONS: Record<string, { continent: string; subregion: string }> = {
  "CR": {
    "continent": "North America",
    "subregion": "Central America"
  },
  "NI": {
    "continent": "North America",
    "subregion": "Central America"
  },
  "HT": {
    "continent": "North America",
    "subregion": "Caribbean"
  },
  "DO": {
    "continent": "North America",
    "subregion": "Caribbean"
  },
  "SV": {
    "continent": "North America",
    "subregion": "Central America"
  },
  "GT": {
    "continent": "North America",
    "subregion": "Central America"
  },
  "CU": {
    "continent": "North America",
    "subregion": "Caribbean"
  },
  "HN": {
    "continent": "North America",
    "subregion": "Central America"
  },
  "US": {
    "continent": "North America",
    "subregion": "Northern America"
  },
  "CA": {
    "continent": "North America",
    "subregion": "Northern America"
  },
  "MX": {
    "continent": "North America",
    "subregion": "Central America"
  },
  "BZ": {
    "continent": "North America",
    "subregion": "Central America"
  },
  "PA": {
    "continent": "North America",
    "subregion": "Central America"
  },
  "GL": {
    "continent": "North America",
    "subregion": "Northern America"
  },
  "BS": {
    "continent": "North America",
    "subregion": "Caribbean"
  },
  "TT": {
    "continent": "North America",
    "subregion": "Caribbean"
  },
  "PR": {
    "continent": "North America",
    "subregion": "Caribbean"
  },
  "JM": {
    "continent": "North America",
    "subregion": "Caribbean"
  },
  "ID": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "MY": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "CY": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "IN": {
    "continent": "Asia",
    "subregion": "Southern Asia"
  },
  "CN": {
    "continent": "Asia",
    "subregion": "Eastern Asia"
  },
  "IL": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "PS": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "LB": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "SY": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "KR": {
    "continent": "Asia",
    "subregion": "Eastern Asia"
  },
  "KP": {
    "continent": "Asia",
    "subregion": "Eastern Asia"
  },
  "BT": {
    "continent": "Asia",
    "subregion": "Southern Asia"
  },
  "OM": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "UZ": {
    "continent": "Asia",
    "subregion": "Central Asia"
  },
  "KZ": {
    "continent": "Asia",
    "subregion": "Central Asia"
  },
  "TJ": {
    "continent": "Asia",
    "subregion": "Central Asia"
  },
  "MN": {
    "continent": "Asia",
    "subregion": "Eastern Asia"
  },
  "VN": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "KH": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "AE": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "GE": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "AZ": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "TR": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "LA": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "KG": {
    "continent": "Asia",
    "subregion": "Central Asia"
  },
  "AM": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "IQ": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "IR": {
    "continent": "Asia",
    "subregion": "Southern Asia"
  },
  "QA": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "SA": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "PK": {
    "continent": "Asia",
    "subregion": "Southern Asia"
  },
  "TH": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "KW": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "TL": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "BN": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "MM": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "BD": {
    "continent": "Asia",
    "subregion": "Southern Asia"
  },
  "AF": {
    "continent": "Asia",
    "subregion": "Southern Asia"
  },
  "TM": {
    "continent": "Asia",
    "subregion": "Central Asia"
  },
  "JO": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "NP": {
    "continent": "Asia",
    "subregion": "Southern Asia"
  },
  "YE": {
    "continent": "Asia",
    "subregion": "Western Asia"
  },
  "PH": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "LK": {
    "continent": "Asia",
    "subregion": "Southern Asia"
  },
  "TW": {
    "continent": "Asia",
    "subregion": "Eastern Asia"
  },
  "JP": {
    "continent": "Asia",
    "subregion": "Eastern Asia"
  },
  "CL": {
    "continent": "South America",
    "subregion": "South America"
  },
  "BO": {
    "continent": "South America",
    "subregion": "South America"
  },
  "PE": {
    "continent": "South America",
    "subregion": "South America"
  },
  "AR": {
    "continent": "South America",
    "subregion": "South America"
  },
  "SR": {
    "continent": "South America",
    "subregion": "South America"
  },
  "GY": {
    "continent": "South America",
    "subregion": "South America"
  },
  "BR": {
    "continent": "South America",
    "subregion": "South America"
  },
  "UY": {
    "continent": "South America",
    "subregion": "South America"
  },
  "EC": {
    "continent": "South America",
    "subregion": "South America"
  },
  "CO": {
    "continent": "South America",
    "subregion": "South America"
  },
  "PY": {
    "continent": "South America",
    "subregion": "South America"
  },
  "VE": {
    "continent": "South America",
    "subregion": "South America"
  },
  "FK": {
    "continent": "South America",
    "subregion": "South America"
  },
  "ET": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "SS": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "SO": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "KE": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "MW": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "TZ": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "MA": {
    "continent": "Africa",
    "subregion": "Northern Africa"
  },
  "EH": {
    "continent": "Africa",
    "subregion": "Northern Africa"
  },
  "CG": {
    "continent": "Africa",
    "subregion": "Middle Africa"
  },
  "CD": {
    "continent": "Africa",
    "subregion": "Middle Africa"
  },
  "NA": {
    "continent": "Africa",
    "subregion": "Southern Africa"
  },
  "ZA": {
    "continent": "Africa",
    "subregion": "Southern Africa"
  },
  "LY": {
    "continent": "Africa",
    "subregion": "Northern Africa"
  },
  "TN": {
    "continent": "Africa",
    "subregion": "Northern Africa"
  },
  "ZM": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "SL": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "GN": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "LR": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "CF": {
    "continent": "Africa",
    "subregion": "Middle Africa"
  },
  "SD": {
    "continent": "Africa",
    "subregion": "Northern Africa"
  },
  "DJ": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "ER": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "CI": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "ML": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "SN": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "NG": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "BJ": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "AO": {
    "continent": "Africa",
    "subregion": "Middle Africa"
  },
  "BW": {
    "continent": "Africa",
    "subregion": "Southern Africa"
  },
  "ZW": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "TD": {
    "continent": "Africa",
    "subregion": "Middle Africa"
  },
  "DZ": {
    "continent": "Africa",
    "subregion": "Northern Africa"
  },
  "MZ": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "SZ": {
    "continent": "Africa",
    "subregion": "Southern Africa"
  },
  "BI": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "RW": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "UG": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "LS": {
    "continent": "Africa",
    "subregion": "Southern Africa"
  },
  "CM": {
    "continent": "Africa",
    "subregion": "Middle Africa"
  },
  "GA": {
    "continent": "Africa",
    "subregion": "Middle Africa"
  },
  "NE": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "BF": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "TG": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "GH": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "GW": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "EG": {
    "continent": "Africa",
    "subregion": "Northern Africa"
  },
  "MR": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "GQ": {
    "continent": "Africa",
    "subregion": "Middle Africa"
  },
  "GM": {
    "continent": "Africa",
    "subregion": "Western Africa"
  },
  "MG": {
    "continent": "Africa",
    "subregion": "Eastern Africa"
  },
  "FR": {
    "continent": "Europe",
    "subregion": "Western Europe"
  },
  "UA": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "BY": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "LT": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "RU": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "CZ": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "DE": {
    "continent": "Europe",
    "subregion": "Western Europe"
  },
  "EE": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "LV": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "NO": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "SE": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "FI": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "LU": {
    "continent": "Europe",
    "subregion": "Western Europe"
  },
  "BE": {
    "continent": "Europe",
    "subregion": "Western Europe"
  },
  "MK": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "AL": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "XK": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "ES": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "DK": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "RO": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "HU": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "SK": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "PL": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "IE": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "GB": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "GR": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "AT": {
    "continent": "Europe",
    "subregion": "Western Europe"
  },
  "IT": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "CH": {
    "continent": "Europe",
    "subregion": "Western Europe"
  },
  "NL": {
    "continent": "Europe",
    "subregion": "Western Europe"
  },
  "RS": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "HR": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "SI": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "BG": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "ME": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "BA": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "PT": {
    "continent": "Europe",
    "subregion": "Southern Europe"
  },
  "MD": {
    "continent": "Europe",
    "subregion": "Eastern Europe"
  },
  "IS": {
    "continent": "Europe",
    "subregion": "Northern Europe"
  },
  "PG": {
    "continent": "Oceania",
    "subregion": "Melanesia"
  },
  "AU": {
    "continent": "Oceania",
    "subregion": "Australia and New Zealand"
  },
  "FJ": {
    "continent": "Oceania",
    "subregion": "Melanesia"
  },
  "NZ": {
    "continent": "Oceania",
    "subregion": "Australia and New Zealand"
  },
  "NC": {
    "continent": "Oceania",
    "subregion": "Melanesia"
  },
  "SB": {
    "continent": "Oceania",
    "subregion": "Melanesia"
  },
  "VU": {
    "continent": "Oceania",
    "subregion": "Melanesia"
  },
  "AQ": {
    "continent": "Antarctica",
    "subregion": "Antarctica"
  },
  "TF": {
    "continent": "Seven seas (open ocean)",
    "subregion": "Seven seas (open ocean)"
  },
  "BM": {
    "continent": "North America",
    "subregion": "Northern America"
  },
  "CC": {
    "continent": "Oceania",
    "subregion": "Australia and New Zealand"
  },
  "CX": {
    "continent": "Oceania",
    "subregion": "Australia and New Zealand"
  },
  "GF": {
    "continent": "South America",
    "subregion": "South America"
  },
  "HK": {
    "continent": "Asia",
    "subregion": "Eastern Asia"
  },
  "KY": {
    "continent": "North America",
    "subregion": "Caribbean"
  },
  "MO": {
    "continent": "Asia",
    "subregion": "Eastern Asia"
  },
  "PM": {
    "continent": "North America",
    "subregion": "Northern America"
  },
  "SG": {
    "continent": "Asia",
    "subregion": "South-Eastern Asia"
  },
  "VI": {
    "continent": "North America",
    "subregion": "Caribbean"
  }
};
