import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

type Feature = {
  properties: {
    iso_a2: string;
    name_en: string;
    name: string;
    [key: string]: unknown;
  };
  geometry: {
    type: string;
    coordinates: unknown;
  };
};

type FeatureCollection = {
  features: Feature[];
};

function flattenCoordinates(coords: unknown): number[][] {
  const result: number[][] = [];

  function walk(c: unknown) {
    if (!Array.isArray(c)) return;
    if (c.length === 2 && typeof c[0] === "number" && typeof c[1] === "number") {
      result.push(c as number[]);
      return;
    }
    for (const item of c) {
      walk(item);
    }
  }

  walk(coords);
  return result;
}

function computeCentroid(coords: number[][]): { lat: number; lng: number } {
  if (coords.length === 0) return { lat: 0, lng: 0 };

  let sumLat = 0;
  let sumLng = 0;
  for (const [lng, lat] of coords) {
    sumLat += lat;
    sumLng += lng;
  }

  return {
    lat: Math.round((sumLat / coords.length) * 1000) / 1000,
    lng: Math.round((sumLng / coords.length) * 1000) / 1000,
  };
}

const geoJsonPath = resolve(__dirname, "../public/data/world-countries.geo.json");
const geoJson: FeatureCollection = JSON.parse(readFileSync(geoJsonPath, "utf-8"));

const centroids: Record<string, { lat: number; lng: number }> = {};
const countryNames: Record<string, string> = {};

for (const feature of geoJson.features) {
  const code = feature.properties.iso_a2;
  if (!code || code === "-99") continue;

  const name = feature.properties.name_en || feature.properties.name;
  const coords = flattenCoordinates(feature.geometry.coordinates);
  const centroid = computeCentroid(coords);

  centroids[code] = centroid;
  countryNames[code] = name;
}

// Write worker/data/centroids.ts
const centroidsTs = `// Generated by scripts/generate-centroids.ts — do not edit manually
export const CENTROIDS: Record<string, { lat: number; lng: number }> = ${JSON.stringify(centroids, null, 2)};
`;
writeFileSync(resolve(__dirname, "../worker/data/centroids.ts"), centroidsTs);

// Write src/entities/country/lib/countries.ts
const countriesTs = `// Generated by scripts/generate-centroids.ts — do not edit manually
export const COUNTRY_NAMES: Record<string, string> = ${JSON.stringify(countryNames, null, 2)};
`;
writeFileSync(
  resolve(__dirname, "../src/entities/country/lib/countries.ts"),
  countriesTs
);

console.log(`Generated centroids for ${Object.keys(centroids).length} countries`);
