import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

type Feature = {
  properties: {
    iso_a2: string;
    name_en: string;
    name: string;
    [key: string]: unknown;
  };
  geometry: {
    type: string;
    coordinates: unknown;
  };
};

/**
 * Natural Earth leaves iso_a2 as "-99" for a few disputed//special cases and
 * spells Taiwan "CN-TW". eBird reports these as plain ISO 3166-1 alpha-2, so
 * recover the code from adm0_a3 (or the odd spelling) to keep them usable.
 */
const CODE_OVERRIDES: Record<string, string> = {
  "CN-TW": "TW",
  FRA: "FR",
  NOR: "NO",
  KOS: "XK",
};

/**
 * Territories eBird reports but this low-resolution world map omits entirely.
 * Centroids are approximate; they only feed distance scoring and hint text.
 */
const EXTRA_COUNTRIES: Record<
  string,
  { name: string; continent: string; subregion: string; lat: number; lng: number }
> = {
  BM: { name: "Bermuda", continent: "North America", subregion: "Northern America", lat: 32.307, lng: -64.751 },
  CC: { name: "Cocos (Keeling) Islands", continent: "Oceania", subregion: "Australia and New Zealand", lat: -12.174, lng: 96.871 },
  CX: { name: "Christmas Island", continent: "Oceania", subregion: "Australia and New Zealand", lat: -10.447, lng: 105.69 },
  GF: { name: "French Guiana", continent: "South America", subregion: "South America", lat: 3.934, lng: -53.126 },
  HK: { name: "Hong Kong", continent: "Asia", subregion: "Eastern Asia", lat: 22.352, lng: 114.14 },
  KY: { name: "Cayman Islands", continent: "North America", subregion: "Caribbean", lat: 19.313, lng: -81.255 },
  MO: { name: "Macao", continent: "Asia", subregion: "Eastern Asia", lat: 22.199, lng: 113.544 },
  PM: { name: "Saint Pierre and Miquelon", continent: "North America", subregion: "Northern America", lat: 46.941, lng: -56.271 },
  SG: { name: "Singapore", continent: "Asia", subregion: "South-Eastern Asia", lat: 1.352, lng: 103.82 },
  VI: { name: "United States Virgin Islands", continent: "North America", subregion: "Caribbean", lat: 18.336, lng: -64.896 },
};

function resolveCode(properties: Feature["properties"]): string | null {
  const raw = properties.iso_a2;
  if (raw && CODE_OVERRIDES[raw]) return CODE_OVERRIDES[raw];
  if (raw && raw !== "-99") return raw;

  const adm = properties.adm0_a3 as string | undefined;
  return adm && CODE_OVERRIDES[adm] ? CODE_OVERRIDES[adm] : null;
}

type FeatureCollection = {
  features: Feature[];
};

function flattenCoordinates(coords: unknown): number[][] {
  const result: number[][] = [];

  function walk(c: unknown) {
    if (!Array.isArray(c)) return;
    if (c.length === 2 && typeof c[0] === "number" && typeof c[1] === "number") {
      result.push(c as number[]);
      return;
    }
    for (const item of c) {
      walk(item);
    }
  }

  walk(coords);
  return result;
}

function computeCentroid(coords: number[][]): { lat: number; lng: number } {
  if (coords.length === 0) return { lat: 0, lng: 0 };

  let sumLat = 0;
  let sumLng = 0;
  for (const [lng, lat] of coords) {
    sumLat += lat;
    sumLng += lng;
  }

  return {
    lat: Math.round((sumLat / coords.length) * 1000) / 1000,
    lng: Math.round((sumLng / coords.length) * 1000) / 1000,
  };
}

const geoJsonPath = resolve(__dirname, "../public/data/world-countries.geo.json");
const geoJson: FeatureCollection = JSON.parse(readFileSync(geoJsonPath, "utf-8"));

const centroids: Record<string, { lat: number; lng: number }> = {};
const countryNames: Record<string, string> = {};
const regions: Record<string, { continent: string; subregion: string }> = {};

for (const feature of geoJson.features) {
  const code = resolveCode(feature.properties);
  if (!code) continue;

  const name = feature.properties.name_en || feature.properties.name;
  const coords = flattenCoordinates(feature.geometry.coordinates);
  const centroid = computeCentroid(coords);

  centroids[code] = centroid;
  countryNames[code] = name;
  regions[code] = {
    continent: (feature.properties.continent as string) || "",
    subregion: (feature.properties.subregion as string) || "",
  };
}

// Fill in territories the world map omits (never overwrite real geometry)
for (const [code, extra] of Object.entries(EXTRA_COUNTRIES)) {
  if (centroids[code]) continue;
  centroids[code] = { lat: extra.lat, lng: extra.lng };
  countryNames[code] = extra.name;
  regions[code] = { continent: extra.continent, subregion: extra.subregion };
}

// Write worker/data/centroids.ts
const centroidsTs = `// Generated by scripts/generate-centroids.ts — do not edit manually
export const CENTROIDS: Record<string, { lat: number; lng: number }> = ${JSON.stringify(centroids, null, 2)};
`;
writeFileSync(resolve(__dirname, "../worker/data/centroids.ts"), centroidsTs);

// Write worker/data/regions.ts
const regionsTs = `// Generated by scripts/generate-centroids.ts — do not edit manually
export const REGIONS: Record<string, { continent: string; subregion: string }> = ${JSON.stringify(regions, null, 2)};
`;
writeFileSync(resolve(__dirname, "../worker/data/regions.ts"), regionsTs);

// Write src/entities/country/lib/countries.ts and worker/data/countries.ts
const countriesTs = `// Generated by scripts/generate-centroids.ts — do not edit manually
export const COUNTRY_NAMES: Record<string, string> = ${JSON.stringify(countryNames, null, 2)};

/** Map feature codes that are not ISO 3166-1 alpha-2, keyed by iso_a2 then adm0_a3. */
export const CODE_OVERRIDES: Record<string, string> = ${JSON.stringify(CODE_OVERRIDES, null, 2)};
`;
writeFileSync(
  resolve(__dirname, "../src/entities/country/lib/countries.ts"),
  countriesTs
);
writeFileSync(resolve(__dirname, "../worker/data/countries.ts"), countriesTs);

console.log(`Generated centroids for ${Object.keys(centroids).length} countries`);
