import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

type BirdEntry = {
  speciesCode: string;
  name: string;
  scientificName: string;
  family: string;
  countries: string[];
  difficulty: string;
  image: {
    url: string;
    license: string;
    artist: string;
  };
};

const birdsPath = resolve(__dirname, "../data/birds.json");
const birds: BirdEntry[] = JSON.parse(readFileSync(birdsPath, "utf-8"));

function escapeSql(str: string): string {
  return str.replace(/'/g, "''");
}

const lines: string[] = [];

lines.push("-- Generated by scripts/seed.ts — do not edit manually");
lines.push("");

for (let i = 0; i < birds.length; i++) {
  const b = birds[i];
  const id = i + 1;
  const imageKey = `birds/${b.speciesCode}.jpg`;

  lines.push(
    `INSERT INTO birds (id, species_code, name, scientific_name, family, difficulty, image_key, image_license, image_artist) VALUES (${id}, '${escapeSql(b.speciesCode)}', '${escapeSql(b.name)}', '${escapeSql(b.scientificName)}', '${escapeSql(b.family)}', '${escapeSql(b.difficulty)}', '${escapeSql(imageKey)}', '${escapeSql(b.image.license)}', '${escapeSql(b.image.artist)}');`
  );

  for (const country of b.countries) {
    lines.push(
      `INSERT INTO bird_countries (bird_id, country_code) VALUES (${id}, '${escapeSql(country)}');`
    );
  }
  lines.push("");
}

// D1 does not support explicit transactions in SQL imports

const outPath = resolve(__dirname, "../data/seed.sql");
writeFileSync(outPath, lines.join("\n"));

console.log(`Generated seed.sql with ${birds.length} birds`);
console.log(`Output: ${outPath}`);
console.log("");
console.log("Next steps:");
console.log("  1. wrangler d1 execute DB --file=data/seed.sql");
console.log("  2. Upload images to R2 (manual or extend this script)");
